// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDo2sXJhZe8vtfF177acEPsssezTGXsSmE',
    appId: '1:592988076169:web:aa5bec80f6caddab47ee58',
    messagingSenderId: '592988076169',
    projectId: 'vize-c292f',
    authDomain: 'vize-c292f.firebaseapp.com',
    storageBucket: 'vize-c292f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOYmvLP5iW5l3San-7ZVmor6aTkVa5J7k',
    appId: '1:592988076169:android:daf5c6df04f2248847ee58',
    messagingSenderId: '592988076169',
    projectId: 'vize-c292f',
    storageBucket: 'vize-c292f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHSq1knfoq---yanvOtDWrYb-z3grRDB0',
    appId: '1:592988076169:ios:5e7b731328ae8daa47ee58',
    messagingSenderId: '592988076169',
    projectId: 'vize-c292f',
    storageBucket: 'vize-c292f.appspot.com',
    iosBundleId: 'com.example.firebaseTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHSq1knfoq---yanvOtDWrYb-z3grRDB0',
    appId: '1:592988076169:ios:fd1ff96ec576e1e247ee58',
    messagingSenderId: '592988076169',
    projectId: 'vize-c292f',
    storageBucket: 'vize-c292f.appspot.com',
    iosBundleId: 'com.example.firebaseTest.RunnerTests',
  );
}
